export const SET_WEATHER_INFORMATION = 'SET_WEATHER_INFORMATION';
export const SET_WEATHER_INFORMATION_START = 'SET_WEATHER_INFORMATION_START';
export const SET_RADIO_SELECTED_VALUE = 'SET_RADIO_SELECTED_VALUE';
export const SET_BARCHART_VISIBILITY = 'SET_BARCHART_VISIBILITY';